version: '3.8'

services:
  jun-panel:
    container_name: jun-panel
    # ================= 关键配置 =================
    # 已自动填好你的镜像地址
    image: ghcr.io/wujun81885/jun-panel:latest
    # ==========================================
    
    restart: unless-stopped
    ports:
      # 端口映射: 3030 可改为任何未占用的端口
      - "3030:8000"
    volumes:
      # 数据持久化目录
      - ./data:/app/data
      # 挂载 Docker Socket (启用 Docker 管理功能)
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # 时区
      - TZ=Asia/Shanghai
